doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            sustainability:
                url: '%env(resolve:DATABASE_SUSTAINABILITY_URL)%'
