imports:
  - php

filter:
  paths:
    - src/*
  excluded_paths:
    - vendor/*
    - test/*
    - var/*
    - bin/*
    - config/*
    - docs/*
    - public/*

build:
  image: default-bionic

  dependencies:
    override:
      - composer install --no-scripts --no-interaction

  nodes:
    my-tests:
      environment:
        php:
          version: 8.3.3

    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run

tests:
  override:
    - command: "composer phpunit"
      coverage:
        file: "docs/coverage.clover"
        format: "php-clover"
