build:
  dependencies:
    before:
      - echo "Skip composer install to avoid dependency lock issues"

  environment:
    php:
      version: 8.2

filter:
  paths:
    - src/
    - tests/

tools:
  php_analyzer: true
