build:
  nodes:
    analysis:
      tests:
        override:
          - go-scrutinizer-run
          - js-scrutinizer-run
          - java-scrutinizer-run
          - php-scrutinizer-run
          - py-scrutinizer-run
          - ruby-scrutinizer-run
