var classes = [
    {
        "name": "App\\Repository\\BookRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 27,
        "loc": 34,
        "lloc": 8,
        "mi": 220.1,
        "mIwoC": 171,
        "commentWeight": 49.1,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Repository\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Form\\BookForm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "implements": [],
        "lcom": 2,
        "length": 16,
        "vocabulary": 14,
        "volume": 60.92,
        "difficulty": 0,
        "effort": 0,
        "level": 1.75,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 106.61,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 63.83,
        "mIwoC": 63.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Card\\Card",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSortOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSuit",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNumericValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAce",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 49,
        "vocabulary": 27,
        "volume": 232.99,
        "difficulty": 4.2,
        "effort": 979.61,
        "level": 0.24,
        "bugs": 0.08,
        "time": 54,
        "intelligentContent": 55.41,
        "number_operators": 12,
        "number_operands": 37,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 22,
        "loc": 64,
        "lloc": 42,
        "mi": 87.3,
        "mIwoC": 47.88,
        "commentWeight": 39.42,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.14,
        "relativeSystemComplexity": 4.14,
        "totalStructuralComplexity": 7,
        "totalDataComplexity": 22,
        "totalSystemComplexity": 29,
        "package": "App\\Card\\",
        "pageRank": 0.42,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Card\\CardGraphic",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getUnicode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Card\\Card"
        ],
        "parents": [
            "App\\Card\\Card"
        ],
        "implements": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 16,
        "volume": 100,
        "difficulty": 3,
        "effort": 300,
        "level": 0.33,
        "bugs": 0.03,
        "time": 17,
        "intelligentContent": 33.33,
        "number_operators": 7,
        "number_operands": 18,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 6,
        "loc": 17,
        "lloc": 11,
        "mi": 102.67,
        "mIwoC": 62.88,
        "commentWeight": 39.79,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "App\\Card\\",
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Card\\DeckOfCards",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shuffle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "draw",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCards",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "drawOne",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 9,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Card\\CardGraphic",
            "App\\Card\\Card",
            "App\\Card\\Card",
            "RuntimeException",
            "App\\Card\\CardGraphic",
            "App\\Card\\Card"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 93,
        "vocabulary": 31,
        "volume": 460.74,
        "difficulty": 4.18,
        "effort": 1925.24,
        "level": 0.24,
        "bugs": 0.15,
        "time": 107,
        "intelligentContent": 110.26,
        "number_operators": 15,
        "number_operands": 78,
        "number_operators_unique": 3,
        "number_operands_unique": 28,
        "cloc": 37,
        "loc": 93,
        "lloc": 56,
        "mi": 83.45,
        "mIwoC": 42.01,
        "commentWeight": 41.45,
        "kanDefect": 1.21,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.43,
        "relativeSystemComplexity": 5.43,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 38,
        "package": "App\\Card\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Card\\CardHand",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCards",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Card\\Card"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 12,
        "loc": 25,
        "lloc": 13,
        "mi": 111.95,
        "mIwoC": 68.01,
        "commentWeight": 43.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "App\\Card\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Book",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIsbn",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIsbn",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAuthor",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAuthor",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setImage",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLanguage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setLanguage",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPages",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPages",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPublishedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPublishedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPublisher",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPublisher",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 17,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 9,
        "nbMethodsSetters": 8,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "DateTimeInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 73,
        "vocabulary": 16,
        "volume": 292,
        "difficulty": 3.43,
        "effort": 1001.14,
        "level": 0.29,
        "bugs": 0.1,
        "time": 56,
        "intelligentContent": 85.17,
        "number_operators": 25,
        "number_operands": 48,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 12,
        "loc": 101,
        "lloc": 89,
        "mi": 65.53,
        "mIwoC": 40.08,
        "commentWeight": 25.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 17.47,
        "relativeSystemComplexity": 17.47,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 297,
        "totalSystemComplexity": 297,
        "package": "App\\Entity\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Game\\Game21",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "startNewRound",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "placeBet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBet",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlayerMoney",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBankMoney",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyResult",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMatchOver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "playerDraw",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAceValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAceChoices",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "playerStands",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPlayerStanding",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bankTurn",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlayerHand",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBankHand",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlayerValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBankValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isGameOver",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWinner",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateValue",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 21,
        "nbMethods": 14,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 7,
        "nbMethodsSetters": 0,
        "wmc": 41,
        "ccn": 28,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Card\\DeckOfCards",
            "App\\Card\\CardHand",
            "App\\Card\\CardHand",
            "App\\Card\\DeckOfCards",
            "App\\Card\\CardHand",
            "App\\Card\\CardHand",
            "InvalidArgumentException",
            "App\\Card\\CardHand",
            "App\\Card\\CardHand",
            "App\\Card\\CardHand"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 216,
        "vocabulary": 35,
        "volume": 1107.93,
        "difficulty": 54.74,
        "effort": 60644.32,
        "level": 0.02,
        "bugs": 0.37,
        "time": 3369,
        "intelligentContent": 20.24,
        "number_operators": 86,
        "number_operands": 130,
        "number_operators_unique": 16,
        "number_operands_unique": 19,
        "cloc": 78,
        "loc": 244,
        "lloc": 166,
        "mi": 64.89,
        "mIwoC": 26.49,
        "commentWeight": 38.41,
        "kanDefect": 1.59,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 1.84,
        "relativeSystemComplexity": 101.84,
        "totalStructuralComplexity": 2100,
        "totalDataComplexity": 38.64,
        "totalSystemComplexity": 2138.64,
        "package": "App\\Game\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Controller\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 13,
        "volume": 48.11,
        "difficulty": 0.5,
        "effort": 24.05,
        "level": 2,
        "bugs": 0.02,
        "time": 1,
        "intelligentContent": 96.21,
        "number_operators": 1,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 12,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 93.07,
        "mIwoC": 68.39,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 11,
        "vocabulary": 11,
        "volume": 38.05,
        "difficulty": 0.5,
        "effort": 19.03,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 76.11,
        "number_operators": 1,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 93.79,
        "mIwoC": 69.1,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\CardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shuffle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "draw",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "drawNumber",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "viewSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteSession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 19,
        "ccnMethodMax": 7,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "App\\Card\\CardHand"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 304,
        "vocabulary": 102,
        "volume": 2028.42,
        "difficulty": 13.04,
        "effort": 26457.62,
        "level": 0.08,
        "bugs": 0.68,
        "time": 1470,
        "intelligentContent": 155.51,
        "number_operators": 64,
        "number_operands": 240,
        "number_operators_unique": 10,
        "number_operands_unique": 92,
        "cloc": 8,
        "loc": 115,
        "lloc": 107,
        "mi": 49.89,
        "mIwoC": 30.02,
        "commentWeight": 19.87,
        "kanDefect": 1.01,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 196.82,
        "totalStructuralComplexity": 1568,
        "totalDataComplexity": 6.53,
        "totalSystemComplexity": 1574.53,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ApiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllBooks",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBookByIsbn",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "App\\Repository\\BookRepository",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "App\\Repository\\BookRepository"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 163,
        "vocabulary": 65,
        "volume": 981.65,
        "difficulty": 3.73,
        "effort": 3657.42,
        "level": 0.27,
        "bugs": 0.33,
        "time": 203,
        "intelligentContent": 263.47,
        "number_operators": 9,
        "number_operands": 154,
        "number_operators_unique": 3,
        "number_operands_unique": 62,
        "cloc": 3,
        "loc": 27,
        "lloc": 24,
        "mi": 73.36,
        "mIwoC": 48.67,
        "commentWeight": 24.69,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 169.43,
        "totalStructuralComplexity": 507,
        "totalDataComplexity": 1.29,
        "totalSystemComplexity": 508.29,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\QuoteApiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "quote",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\JsonResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 14,
        "volume": 60.92,
        "difficulty": 1.17,
        "effort": 71.07,
        "level": 0.86,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 52.22,
        "number_operators": 2,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 90.08,
        "mIwoC": 66.55,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\MetricsController",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0.5,
        "effort": 9.83,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 39.3,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 95.8,
        "mIwoC": 71.11,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\BookController",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "new",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\BookRepository",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\ORM\\EntityManagerInterface",
            "App\\Entity\\Book",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Entity\\Book",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\Book",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Entity\\Book",
            "Doctrine\\ORM\\EntityManagerInterface"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 96,
        "vocabulary": 29,
        "volume": 466.37,
        "difficulty": 8.33,
        "effort": 3886.38,
        "level": 0.12,
        "bugs": 0.16,
        "time": 216,
        "intelligentContent": 55.96,
        "number_operators": 16,
        "number_operands": 80,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 6,
        "loc": 48,
        "lloc": 42,
        "mi": 71.13,
        "mIwoC": 45.1,
        "commentWeight": 26.04,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 196.6,
        "totalStructuralComplexity": 980,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 983,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ReportController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0.5,
        "effort": 5.8,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 97.4,
        "mIwoC": 72.71,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\Game\\GameApiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "gameStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Game\\Game21"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 41,
        "vocabulary": 21,
        "volume": 180.09,
        "difficulty": 4.24,
        "effort": 762.71,
        "level": 0.24,
        "bugs": 0.06,
        "time": 42,
        "intelligentContent": 42.52,
        "number_operators": 5,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 17,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 86.11,
        "mIwoC": 62.58,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 196.13,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 196.13,
        "package": "App\\Controller\\Game\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\Game\\GameController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "doc",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "play",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "draw",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stand",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ace",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 14,
        "ccnMethodMax": 9,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Game\\Game21",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Game\\Game21",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 180,
        "vocabulary": 51,
        "volume": 1021.04,
        "difficulty": 11.93,
        "effort": 12182.82,
        "level": 0.08,
        "bugs": 0.34,
        "time": 677,
        "intelligentContent": 85.57,
        "number_operators": 30,
        "number_operands": 150,
        "number_operators_unique": 7,
        "number_operands_unique": 44,
        "cloc": 8,
        "loc": 82,
        "lloc": 74,
        "mi": 59.53,
        "mIwoC": 36.27,
        "commentWeight": 23.26,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 729,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 729.39,
        "totalStructuralComplexity": 5832,
        "totalDataComplexity": 3.14,
        "totalSystemComplexity": 5835.14,
        "package": "App\\Controller\\Game\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\LuckyController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 23,
        "volume": 135.71,
        "difficulty": 1.24,
        "effort": 168.02,
        "level": 0.81,
        "bugs": 0.05,
        "time": 9,
        "intelligentContent": 109.61,
        "number_operators": 4,
        "number_operands": 26,
        "number_operators_unique": 2,
        "number_operands_unique": 21,
        "cloc": 1,
        "loc": 12,
        "lloc": 11,
        "mi": 83.84,
        "mIwoC": 62.22,
        "commentWeight": 21.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\LibraryController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Doctrine\\ORM\\EntityManagerInterface",
            "DateTime",
            "DateTime",
            "DateTime",
            "App\\Entity\\Book",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 97,
        "vocabulary": 40,
        "volume": 516.23,
        "difficulty": 2.45,
        "effort": 1263.4,
        "level": 0.41,
        "bugs": 0.17,
        "time": 70,
        "intelligentContent": 210.93,
        "number_operators": 4,
        "number_operands": 93,
        "number_operators_unique": 2,
        "number_operands_unique": 38,
        "cloc": 2,
        "loc": 30,
        "lloc": 28,
        "mi": 68.64,
        "mIwoC": 49.17,
        "commentWeight": 19.47,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.16,
        "relativeSystemComplexity": 225.16,
        "totalStructuralComplexity": 450,
        "totalDataComplexity": 0.31,
        "totalSystemComplexity": 450.31,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ApiCardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "apiDeck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiShuffle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiDrawOne",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiDrawNumber",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apiDeal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 9,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface",
            "App\\Card\\DeckOfCards"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 173,
        "vocabulary": 47,
        "volume": 960.94,
        "difficulty": 16.58,
        "effort": 15931.44,
        "level": 0.06,
        "bugs": 0.32,
        "time": 885,
        "intelligentContent": 57.96,
        "number_operators": 33,
        "number_operands": 140,
        "number_operators_unique": 9,
        "number_operands_unique": 38,
        "cloc": 5,
        "loc": 57,
        "lloc": 52,
        "mi": 62.62,
        "mIwoC": 40.47,
        "commentWeight": 22.15,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.96,
        "relativeSystemComplexity": 64.96,
        "totalStructuralComplexity": 320,
        "totalDataComplexity": 4.78,
        "totalSystemComplexity": 324.78,
        "package": "App\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]